# Generated by Django 4.2.11 on 2024-04-09 21:31

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('kcal', models.IntegerField()),
                ('type', models.IntegerField(choices=[(0, 'Starter'), (1, 'Entree'), (2, 'Dessert'), (3, 'Drink')], default=0)),
                ('photo', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('badge', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
